### ISSUE TITLE
Magnet atop Livestock crash

### ISSUE THREAD

**Issue by mason3ck** [Lothrazar/GardenTools#4]
Minecraft Version:  1.16.5

Forge Version:  36.1.16

Mod Version: 1.1.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Placed a magnet block atop a livestock block, server immediately crashed and wont launch

Log file link:

[crash-2021-07-09_13.26.21-server.txt](https://github.com/Lothrazar/GardenTools/files/6793386/crash-2021-07-09_13.26.21-server.txt)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/gardening-tools/files/3386131
