### ISSUE TITLE
Fatal error on launch (Forge versions 37.0.32-37.0.40)

### ISSUE THREAD

**Issue by HalcyonSeas73** [Lothrazar/GardenTools#5]
Minecraft Version: 1.17.1

Forge Version: 37.0.32 and higher

Mod Version: 1.1.2

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):Fatal error on launch; Exception message: java.lang.ClassNotFoundException: net.minecraftforge.common.ToolType

Log file link: https://pastebin.com/uHxJrbb0

**Comment by Lothrazar** [comment]
oh something with tool types changed? looks like. could affect a few mods. i guess mods built on 37.0.13 have to update
